---
 - name: apt-get update
   apt: update_cache=yes cache_valid_time=86400

 - name: common packages
   action: apt pkg={{ item }} state=latest
   with_items:
     - curl
     - vim
     - git

 - name: create usergroup wordpress
   group: name={{usergroup}} state=present

 - name: create user wordpress
   user: name={{usergroup}} groups={{usergroup}},www-data

 - name: copy private key for git repo
   copy: src=id_rsa dest=/home/{{usergroup}}/.ssh/ mode=400